# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: è§è´¤æ€é½ç„‰ï¼Œè§ä¸è´¤è€Œå†…è‡ªçœä¹Ÿã€‚
description: > # this means to ignore newlines until "baseurl:"
  åŸºäº Jekyll çš„ Github Pages ä¸ªäººåšå®¢ç½‘ç«™ï¼Œè®°å½•å·¥ä½œç”Ÿæ´»ä¸å­¦ä¹ ä¸­çš„ç‚¹ç‚¹æ»´æ»´ã€‚ã€‚ã€‚ğŸ±
baseurl: ""
url: "https://bobcatzoo.github.io"
github_repo: "https://github.com/bobcatzoo/bobcatzoo.github.io"
github_profile: "https://github.com/bobcatzoo"
permalink: /:year/:month/:day/:title
repository: 
paginate: 5 #æ¯é¡µæ˜¾ç¤º5ç¯‡æ–‡ç« 

# MatJek specific configurations
#github_profile: "https://github.com/bobcatzoo"
user: "Alex"
user_email: "bobcatzoo@outlook.com"
contact_url: "https://forms.office.com/r/jMwZkxUzF9" #ç”¨äºcontacté¡µé¢
google_tracking_id: 
google_site_verification: 
disqus_shortname: "alex"

douban_username:  # ä½ çš„è±†ç“£id
twitter_username: realJarryCat
github_username: 
facebook_username: 
weibo_username: 
zhihu_username: tomcat-63-60

# valine è¯„è®ºæ’ä»¶é…ç½®
valine:
  leancloud_appid: "lPecgqbFAAuuCvD2R2fMNbbC-gzGzoHsz"
  leancloud_appkey: "VSbc5y1DaHu1Sn5PSD1g8QMA"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true
lang: zh_CN